# Generated by Django 5.2.10 on 2026-03-09 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_ejemplo_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejemplo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.producto'),
        ),
    ]
