# Generated by Django 5.2.10 on 2026-03-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_ejemplo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='stock',
        ),
    ]
